### ISSUE TITLE
Extract ACS security code in own artifact

### ISSUE THREAD

**Issue by JMayrbaeurl** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#1]
Please extract the sources for the ACS based authentication in an extra Java artifact. With a Maven build. This makes it possible to use ACS in 'normal' Java web applications without the need of having to use a Windows Azure Deployment project. Other possibility would be to include it in the Azure Java SDK.

I've done this for a demo, we're currently preparing for the GOTO Conference in Zurich. It's accessible by using the following Maven dependency:

		<dependency>
			<groupId>com.microsoft.windowsazure</groupId>
			<artifactId>microsoft-windowsazure-web</artifactId>
			<version>0.0.1-SNAPSHOT</version>
		</dependency>

and the repository:

		<repository>
			<id>jm-internal</id>
			<url>http://jmmvn.azurewebsites.net/repo/</url>
			<releases>
				<enabled>true</enabled>
			</releases>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>

**Comment by martinsawicki** [comment]
treating this issue as obsolete, especially since ACS is a deprecated technology in Azure now.
