### ISSUE TITLE
some class is missing   in 2.2.1 source

### ISSUE THREAD

**Issue by takekazuomi** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#10]
1. CertificateUpload.java dose not include
2. Certificates.class and Certificate.class is missing referenced by ModelFactory.java
I checked  RELEASE/2.2.1 and master branch.

https://github.com/MSOpenTech/WindowsAzureToolkitForEclipseWithJava/tree/RELEASES/v2.2.1/PluginsAndFeatures/com.persistent.winazure.eclipseplugin/src/com/gigaspaces/azure/model

I can't build it.

**Comment by martinsawicki** [comment]
closing as fixed
