### ISSUE TITLE
No way to downgrade?

### ISSUE THREAD

**Issue by jonlimx** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#12]
1.	Seems like Azure SDK should be compatible with  Azure Toolkit for Eclipse. 
2.	Only Azure SDK below 2.4 contains caching components for Java Eclipse project. Say we can use Azure SDK 2.3, but we have no way to install Azure Toolkit for Eclipse. Latest(2.5) Azure Toolkit for Eclipse is installed via http://dl.msopentech.com/eclipse.

**Comment by martinsawicki** [comment]
Probably an obsolete issue. the latest SDK 2.8 contains the Caching components and the latest Azure Toolkit for Eclipse still supports it.
