### ISSUE TITLE
Installation failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by serenayuq** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#13]
According to MSDN, https://msdn.microsoft.com/en-us/library/azure/hh690946 , this toolkit could be installed on Ubuntu 14.04 
but when we actually try to install it, we would encounter failures. 
Cannot complete the install because some dependencies are not satisfiable com.microsoftopentechnologies.windowsazure.tools.sdk.feature.feature.group
[0.7.0.201501291852] cannot be installed in this environment because its filter is not applicable.

could you clarify if this toolkit could be installed on Ubuntu 14.04 or not ?

Many Thanks

**Comment by martinsawicki** [comment]
it should work by now -- tested on Ubuntu 14.04.
