### ISSUE TITLE
Failed to install it in Ubuntu 14.04/14.10

### ISSUE THREAD

**Issue by jonlimx** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#14]
Seems like it doesn't make sense to install this tool in Linux, cuz it depends on Azure SDK which only has windsows Version when publishing Java to Azure Cloud service. However, when following https://msdn.microsoft.com/library/azure/hh690946/, I am told that we can install it in Ubuntu 14.04. But When I tried that, I got the following error:
Cannot complete the install because some dependencies are not satisfiable com.microsoftopentechnologies.windowsazure.tools.sdk.feature.feature.group
[0.7.0.201501291852] cannot be installed in this environment because its filter is not applicable.

Any ideas?

**Comment by martinsawicki** [comment]
Linux (and Mac) support is now available in Azure Toolkit for Eclipse (as or last March)
