### ISSUE TITLE
Failed to upload WAS war on Windows 8.1

### ISSUE THREAD

**Issue by normalian** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#15]
I can't upload *.cspkg file when I select WebSphere 8.5 as my AppServer and I got below error.
`
[windowsazurepackage] cspack.exe: Error   : 指定されたパス、ファイル名、またはその両方が長すぎます。完全限定型名は 260 文字未満で指定し、ディレクトリ名は 248 未満で指定してください。
`
This error is same with below error log
`
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters. 
`

After I got this error, I have tried below ways, but I got same error like as the first.
* Move to Eclipse Project from c:\opt\workspace\HelloAzure to c:\HelloAzure
* Run cspack.exe as command line
`
>cspack.exe D:\HelloAzure\ServiceDefinition.csdef /role:WorkerRole1;D:\HelloAzure\WorkerRole1\approot /rolePropertiesFile:WorkerRole1;D:\HelloAzure\.rolePropertiesOS3 /out:D:\HelloAzure\deploy\WindowsAzurePackage.cspkg
`
* Run cspack.exe as command line deleting /rolePropertiesFile
`
>cspack.exe D:\HelloAzure\ServiceDefinition.csdef /role:WorkerRole1;D:\HelloAzure\WorkerRole1\approot  /out:D:\HelloAzure\deploy\WindowsAzurePackage.cspkg
`

I guess this error is caused by the copying WAS profile into WorkerRole1\approot. How can I upload *cspack file using WAS?

**Comment by martinsawicki** [comment]
WAS is too large and complex to be supported in Cloud Services. There are VM images in the Azure portal gallery with WAS. Or it can be installed on a blank Windows or Linux image.
(the more lightweight WAS Liberty can be used in the Eclipse Toolkit and deployed to Azure cloud services though)
