### ISSUE TITLE
Tomcat 7.0.42 + JDK1.7.0_71 + SSLOffloading + >2 Instances = No longer working

### ISSUE THREAD

**Issue by rdr1983** [MSOpenTech/WindowsAzureToolkitForEclipseWithJava#16]
Hi, as I mentioned on the title, there is a problem that appeared the March 21th in an Azure Cloud Service, EAST US region, I have an application deployment using the Eclipse Plugin Version 2.5.0.201411120147, including a Tomcat Server, Java JDK and some settings that mmake use of SSL Offloading and the service has 2 instances configured, nobody makes changes to that configuration in a long time, so, for an unknow reason for us, in March 21 at 4:45 pm +6 (Mexico Central Time) the azure cloud service was automatically restarted and when it appears in Available Status, the IIS services are down, the internal Tomcat Service with the Java application is UP and working internally, checked thru the remote desktop connection, it looks like something related to the ARR configuration included in the plug-in and is not compatible with the last windows 20XX image used as template for cloud services. I may appreciate so much if you can do a test with a generic deployment with some setting as I mentioned and see what is the result. Thank you.

**Comment by rdr1983** [comment]
UPDATE: The Azure Plugin fails the deployment with the latest version of the Azure S.O. Windows 2008 R2 Family 2 (2.38), I didn't research where is the problem, so changing the setting in the azure portal in the S.O. family and version to 2.37 serves as walkaround if you have the "Automatic" setting.

**Comment by martinsawicki** [comment]
fixed a while back
